# Linear Model

LinearRegression fits a linear model with coefficients 
 to minimize the residual sum of squares between the observed targets in the dataset, and the targets predicted by the linear approximation.

In [1]:
from sklearn import linear_model

In [2]:
reg = linear_model.LinearRegression()
reg

LinearRegression()

In [4]:
reg.fit([[0, 0], [1, 1], [2, 2]], [0, 1, 2])

LinearRegression()

In [5]:
reg.coef_

array([0.5, 0.5])

##  Ridge regression and classification

Ridge regression addresses some of the problems of Ordinary Least Squares by imposing a penalty on the size of the coefficients. The ridge coefficients minimize a penalized residual sum of squares:

 


In [6]:
from sklearn import linear_model

In [7]:
reg = linear_model.Ridge(alpha = .5)

In [8]:
reg.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1])

Ridge(alpha=0.5)

In [9]:
reg.coef_

array([0.34545455, 0.34545455])

In [10]:
reg.intercept_

0.13636363636363638

###### The Ridge regressor has a classifier variant: RidgeClassifier. This classifier first converts binary targets to {-1, 1} and then treats the problem as a regression task, optimizing the same objective as above. The predicted class corresponds to the sign of the regressor’s prediction. For multiclass classification, the problem is treated as multi-output regression, and the predicted class corresponds to the output with the highest value.

## Setting the regularization parameter: leave-one-out Cross-Validation

RidgeCV implements ridge regression with built-in cross-validation of the alpha parameter. The object works in the same way as GridSearchCV except that it defaults to Leave-One-Out Cross-Validation:

In [12]:
import numpy as np
from sklearn import linear_model

In [13]:
reg = linear_model.RidgeCV(alphas = np.logspace(-6,6,13))
reg

RidgeCV(alphas=array([1.e-06, 1.e-05, 1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01,
       1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))

In [14]:
reg.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1])

RidgeCV(alphas=array([1.e-06, 1.e-05, 1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01,
       1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06]))

In [15]:
reg.alpha_

0.01

###### Specifying the value of the cv attribute will trigger the use of cross-validation with GridSearchCV, for example cv=10 for 10-fold cross-validation, rather than Leave-One-Out Cross-Validation.

# Lasso

The Lasso is a linear model that estimates sparse coefficients. It is useful in some contexts due to its tendency to prefer solutions with fewer non-zero coefficients, effectively reducing the number of features upon which the given solution is dependent. For this reason Lasso and its variants are fundamental to the field of compressed sensing. Under certain conditions, it can recover the exact set of non-zero coefficients

The implementation in the class Lasso uses coordinate descent as the algorithm to fit the coefficients

In [16]:
from sklearn import linear_model

In [17]:
reg = linear_model.Lasso(alpha=0.1)

In [18]:
reg.fit([[0, 0], [1, 1]], [0, 1])

Lasso(alpha=0.1)

In [19]:
reg.predict([[1, 1]])

array([0.8])

In [20]:
reg.predict([[0, 1]])

array([0.2])

In [21]:
reg.predict([[0,0]])

array([0.2])

In [22]:
reg.predict([[1, 0]])

array([0.8])

# Comparison with the regularization parameter of SVM

###### The equivalence between alpha and the regularization parameter of SVM, C is given by alpha = 1 / C or alpha = 1 / (n_samples * C), depending on the estimator and the exact objective function optimized by the model.



# Multi-task Lasso